apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nimbus-netpol.fullname" . }}-clusterrole
rules:
  - apiGroups:
      - intent.security.nimbus.com
    resources:
      - nimbuspolicies
      - clusternimbuspolicies
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - intent.security.nimbus.com
    resources:
      - nimbuspolicies/status
      - clusternimbuspolicies/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - create
      - list
      - get
      - update
      - watch
