# permissions for end users to edit nimbuspolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nimbuspolicy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nimbus
    app.kubernetes.io/part-of: nimbus
    app.kubernetes.io/managed-by: kustomize
  name: nimbuspolicy-editor-role
rules:
- apiGroups:
  - intent.security.nimbus.com
  resources:
  - nimbuspolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - intent.security.nimbus.com
  resources:
  - nimbuspolicies/status
  verbs:
  - get
