apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nimbus-kubearmor.fullname" . }}
  labels:
    {{- include "nimbus-kubearmor.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "nimbus-kubearmor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nimbus-kubearmor.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "nimbus-kubearmor.serviceAccountName" . }}
      containers:
        - name: {{ .Values.fullnameOverride }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
