apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nimbus-kubearmor.fullname" . }}-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "nimbus-kubearmor.fullname" . }}-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ include "nimbus-kubearmor.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}