//go:build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0
// Copyright 2023 Authors of Nimbus

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CIDRSet) DeepCopyInto(out *CIDRSet) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CIDRSet.
func (in *CIDRSet) DeepCopy() *CIDRSet {
	if in == nil {
		return nil
	}
	out := new(CIDRSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Intent) DeepCopyInto(out *Intent) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make([]SecurityIntentParams, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Intent.
func (in *Intent) DeepCopy() *Intent {
	if in == nil {
		return nil
	}
	out := new(Intent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchCapability) DeepCopyInto(out *MatchCapability) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchCapability.
func (in *MatchCapability) DeepCopy() *MatchCapability {
	if in == nil {
		return nil
	}
	out := new(MatchCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchDirectory) DeepCopyInto(out *MatchDirectory) {
	*out = *in
	if in.FromSource != nil {
		in, out := &in.FromSource, &out.FromSource
		*out = make([]NimbusFromSource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchDirectory.
func (in *MatchDirectory) DeepCopy() *MatchDirectory {
	if in == nil {
		return nil
	}
	out := new(MatchDirectory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchIntent) DeepCopyInto(out *MatchIntent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchIntent.
func (in *MatchIntent) DeepCopy() *MatchIntent {
	if in == nil {
		return nil
	}
	out := new(MatchIntent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchPath) DeepCopyInto(out *MatchPath) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchPath.
func (in *MatchPath) DeepCopy() *MatchPath {
	if in == nil {
		return nil
	}
	out := new(MatchPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchPattern) DeepCopyInto(out *MatchPattern) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchPattern.
func (in *MatchPattern) DeepCopy() *MatchPattern {
	if in == nil {
		return nil
	}
	out := new(MatchPattern)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchProtocol) DeepCopyInto(out *MatchProtocol) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchProtocol.
func (in *MatchProtocol) DeepCopy() *MatchProtocol {
	if in == nil {
		return nil
	}
	out := new(MatchProtocol)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchSyscall) DeepCopyInto(out *MatchSyscall) {
	*out = *in
	if in.Syscalls != nil {
		in, out := &in.Syscalls, &out.Syscalls
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchSyscall.
func (in *MatchSyscall) DeepCopy() *MatchSyscall {
	if in == nil {
		return nil
	}
	out := new(MatchSyscall)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NimbusFromSource) DeepCopyInto(out *NimbusFromSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NimbusFromSource.
func (in *NimbusFromSource) DeepCopy() *NimbusFromSource {
	if in == nil {
		return nil
	}
	out := new(NimbusFromSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NimbusPolicy) DeepCopyInto(out *NimbusPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NimbusPolicy.
func (in *NimbusPolicy) DeepCopy() *NimbusPolicy {
	if in == nil {
		return nil
	}
	out := new(NimbusPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NimbusPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NimbusPolicyList) DeepCopyInto(out *NimbusPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NimbusPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NimbusPolicyList.
func (in *NimbusPolicyList) DeepCopy() *NimbusPolicyList {
	if in == nil {
		return nil
	}
	out := new(NimbusPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NimbusPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NimbusPolicySpec) DeepCopyInto(out *NimbusPolicySpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	if in.NimbusRules != nil {
		in, out := &in.NimbusRules, &out.NimbusRules
		*out = make([]NimbusRules, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NimbusPolicySpec.
func (in *NimbusPolicySpec) DeepCopy() *NimbusPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NimbusPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NimbusPolicyStatus) DeepCopyInto(out *NimbusPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NimbusPolicyStatus.
func (in *NimbusPolicyStatus) DeepCopy() *NimbusPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(NimbusPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NimbusRules) DeepCopyInto(out *NimbusRules) {
	*out = *in
	in.Rule.DeepCopyInto(&out.Rule)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NimbusRules.
func (in *NimbusRules) DeepCopy() *NimbusRules {
	if in == nil {
		return nil
	}
	out := new(NimbusRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NimbusSelector) DeepCopyInto(out *NimbusSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NimbusSelector.
func (in *NimbusSelector) DeepCopy() *NimbusSelector {
	if in == nil {
		return nil
	}
	out := new(NimbusSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Port) DeepCopyInto(out *Port) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Port.
func (in *Port) DeepCopy() *Port {
	if in == nil {
		return nil
	}
	out := new(Port)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceFilter) DeepCopyInto(out *ResourceFilter) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceFilter.
func (in *ResourceFilter) DeepCopy() *ResourceFilter {
	if in == nil {
		return nil
	}
	out := new(ResourceFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resources) DeepCopyInto(out *Resources) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resources.
func (in *Resources) DeepCopy() *Resources {
	if in == nil {
		return nil
	}
	out := new(Resources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rule) DeepCopyInto(out *Rule) {
	*out = *in
	if in.MatchProtocols != nil {
		in, out := &in.MatchProtocols, &out.MatchProtocols
		*out = make([]MatchProtocol, len(*in))
		copy(*out, *in)
	}
	if in.MatchPaths != nil {
		in, out := &in.MatchPaths, &out.MatchPaths
		*out = make([]MatchPath, len(*in))
		copy(*out, *in)
	}
	if in.MatchDirectories != nil {
		in, out := &in.MatchDirectories, &out.MatchDirectories
		*out = make([]MatchDirectory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MatchPatterns != nil {
		in, out := &in.MatchPatterns, &out.MatchPatterns
		*out = make([]MatchPattern, len(*in))
		copy(*out, *in)
	}
	if in.MatchCapabilities != nil {
		in, out := &in.MatchCapabilities, &out.MatchCapabilities
		*out = make([]MatchCapability, len(*in))
		copy(*out, *in)
	}
	if in.MatchSyscalls != nil {
		in, out := &in.MatchSyscalls, &out.MatchSyscalls
		*out = make([]MatchSyscall, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FromCIDRSet != nil {
		in, out := &in.FromCIDRSet, &out.FromCIDRSet
		*out = make([]CIDRSet, len(*in))
		copy(*out, *in)
	}
	if in.ToPorts != nil {
		in, out := &in.ToPorts, &out.ToPorts
		*out = make([]ToPort, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rule.
func (in *Rule) DeepCopy() *Rule {
	if in == nil {
		return nil
	}
	out := new(Rule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityIntent) DeepCopyInto(out *SecurityIntent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityIntent.
func (in *SecurityIntent) DeepCopy() *SecurityIntent {
	if in == nil {
		return nil
	}
	out := new(SecurityIntent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityIntent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityIntentBinding) DeepCopyInto(out *SecurityIntentBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityIntentBinding.
func (in *SecurityIntentBinding) DeepCopy() *SecurityIntentBinding {
	if in == nil {
		return nil
	}
	out := new(SecurityIntentBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityIntentBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityIntentBindingList) DeepCopyInto(out *SecurityIntentBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecurityIntentBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityIntentBindingList.
func (in *SecurityIntentBindingList) DeepCopy() *SecurityIntentBindingList {
	if in == nil {
		return nil
	}
	out := new(SecurityIntentBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityIntentBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityIntentBindingSpec) DeepCopyInto(out *SecurityIntentBindingSpec) {
	*out = *in
	if in.Intents != nil {
		in, out := &in.Intents, &out.Intents
		*out = make([]MatchIntent, len(*in))
		copy(*out, *in)
	}
	in.Selector.DeepCopyInto(&out.Selector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityIntentBindingSpec.
func (in *SecurityIntentBindingSpec) DeepCopy() *SecurityIntentBindingSpec {
	if in == nil {
		return nil
	}
	out := new(SecurityIntentBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityIntentBindingStatus) DeepCopyInto(out *SecurityIntentBindingStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityIntentBindingStatus.
func (in *SecurityIntentBindingStatus) DeepCopy() *SecurityIntentBindingStatus {
	if in == nil {
		return nil
	}
	out := new(SecurityIntentBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityIntentCIDRSet) DeepCopyInto(out *SecurityIntentCIDRSet) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityIntentCIDRSet.
func (in *SecurityIntentCIDRSet) DeepCopy() *SecurityIntentCIDRSet {
	if in == nil {
		return nil
	}
	out := new(SecurityIntentCIDRSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityIntentFromSource) DeepCopyInto(out *SecurityIntentFromSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityIntentFromSource.
func (in *SecurityIntentFromSource) DeepCopy() *SecurityIntentFromSource {
	if in == nil {
		return nil
	}
	out := new(SecurityIntentFromSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityIntentList) DeepCopyInto(out *SecurityIntentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecurityIntent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityIntentList.
func (in *SecurityIntentList) DeepCopy() *SecurityIntentList {
	if in == nil {
		return nil
	}
	out := new(SecurityIntentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityIntentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityIntentMatchCapability) DeepCopyInto(out *SecurityIntentMatchCapability) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityIntentMatchCapability.
func (in *SecurityIntentMatchCapability) DeepCopy() *SecurityIntentMatchCapability {
	if in == nil {
		return nil
	}
	out := new(SecurityIntentMatchCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityIntentMatchDirectory) DeepCopyInto(out *SecurityIntentMatchDirectory) {
	*out = *in
	if in.FromSource != nil {
		in, out := &in.FromSource, &out.FromSource
		*out = make([]SecurityIntentFromSource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityIntentMatchDirectory.
func (in *SecurityIntentMatchDirectory) DeepCopy() *SecurityIntentMatchDirectory {
	if in == nil {
		return nil
	}
	out := new(SecurityIntentMatchDirectory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityIntentMatchPath) DeepCopyInto(out *SecurityIntentMatchPath) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityIntentMatchPath.
func (in *SecurityIntentMatchPath) DeepCopy() *SecurityIntentMatchPath {
	if in == nil {
		return nil
	}
	out := new(SecurityIntentMatchPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityIntentMatchPattern) DeepCopyInto(out *SecurityIntentMatchPattern) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityIntentMatchPattern.
func (in *SecurityIntentMatchPattern) DeepCopy() *SecurityIntentMatchPattern {
	if in == nil {
		return nil
	}
	out := new(SecurityIntentMatchPattern)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityIntentMatchProtocol) DeepCopyInto(out *SecurityIntentMatchProtocol) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityIntentMatchProtocol.
func (in *SecurityIntentMatchProtocol) DeepCopy() *SecurityIntentMatchProtocol {
	if in == nil {
		return nil
	}
	out := new(SecurityIntentMatchProtocol)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityIntentMatchSyscall) DeepCopyInto(out *SecurityIntentMatchSyscall) {
	*out = *in
	if in.Syscalls != nil {
		in, out := &in.Syscalls, &out.Syscalls
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityIntentMatchSyscall.
func (in *SecurityIntentMatchSyscall) DeepCopy() *SecurityIntentMatchSyscall {
	if in == nil {
		return nil
	}
	out := new(SecurityIntentMatchSyscall)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityIntentParams) DeepCopyInto(out *SecurityIntentParams) {
	*out = *in
	if in.MatchProtocols != nil {
		in, out := &in.MatchProtocols, &out.MatchProtocols
		*out = make([]SecurityIntentMatchProtocol, len(*in))
		copy(*out, *in)
	}
	if in.MatchPaths != nil {
		in, out := &in.MatchPaths, &out.MatchPaths
		*out = make([]SecurityIntentMatchPath, len(*in))
		copy(*out, *in)
	}
	if in.MatchDirectories != nil {
		in, out := &in.MatchDirectories, &out.MatchDirectories
		*out = make([]SecurityIntentMatchDirectory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MatchPatterns != nil {
		in, out := &in.MatchPatterns, &out.MatchPatterns
		*out = make([]SecurityIntentMatchPattern, len(*in))
		copy(*out, *in)
	}
	if in.MatchCapabilities != nil {
		in, out := &in.MatchCapabilities, &out.MatchCapabilities
		*out = make([]SecurityIntentMatchCapability, len(*in))
		copy(*out, *in)
	}
	if in.MatchSyscalls != nil {
		in, out := &in.MatchSyscalls, &out.MatchSyscalls
		*out = make([]SecurityIntentMatchSyscall, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FromCIDRSet != nil {
		in, out := &in.FromCIDRSet, &out.FromCIDRSet
		*out = make([]SecurityIntentCIDRSet, len(*in))
		copy(*out, *in)
	}
	if in.ToPorts != nil {
		in, out := &in.ToPorts, &out.ToPorts
		*out = make([]SecurityIntentToPort, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityIntentParams.
func (in *SecurityIntentParams) DeepCopy() *SecurityIntentParams {
	if in == nil {
		return nil
	}
	out := new(SecurityIntentParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityIntentPort) DeepCopyInto(out *SecurityIntentPort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityIntentPort.
func (in *SecurityIntentPort) DeepCopy() *SecurityIntentPort {
	if in == nil {
		return nil
	}
	out := new(SecurityIntentPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityIntentSpec) DeepCopyInto(out *SecurityIntentSpec) {
	*out = *in
	in.Intent.DeepCopyInto(&out.Intent)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityIntentSpec.
func (in *SecurityIntentSpec) DeepCopy() *SecurityIntentSpec {
	if in == nil {
		return nil
	}
	out := new(SecurityIntentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityIntentStatus) DeepCopyInto(out *SecurityIntentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityIntentStatus.
func (in *SecurityIntentStatus) DeepCopy() *SecurityIntentStatus {
	if in == nil {
		return nil
	}
	out := new(SecurityIntentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityIntentToPort) DeepCopyInto(out *SecurityIntentToPort) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]SecurityIntentPort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityIntentToPort.
func (in *SecurityIntentToPort) DeepCopy() *SecurityIntentToPort {
	if in == nil {
		return nil
	}
	out := new(SecurityIntentToPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Selector) DeepCopyInto(out *Selector) {
	*out = *in
	if in.Any != nil {
		in, out := &in.Any, &out.Any
		*out = make([]ResourceFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.All != nil {
		in, out := &in.All, &out.All
		*out = make([]ResourceFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CEL != nil {
		in, out := &in.CEL, &out.CEL
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Selector.
func (in *Selector) DeepCopy() *Selector {
	if in == nil {
		return nil
	}
	out := new(Selector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToPort) DeepCopyInto(out *ToPort) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]Port, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToPort.
func (in *ToPort) DeepCopy() *ToPort {
	if in == nil {
		return nil
	}
	out := new(ToPort)
	in.DeepCopyInto(out)
	return out
}
