# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Authors of Nimbus

apiVersion: intent.security.nimbus.com/v1
kind: SecurityIntent
metadata:
  name: pkg-mgr-exec-multiple-nsscoped
spec:
  intent:
    id: swDeploymentTools
    action: Block
    mode: strict
---
apiVersion: intent.security.nimbus.com/v1
kind: SecurityIntent
metadata:
  name: unauthorized-sa-token-access-multiple-nsscoped
spec:
  intent:
    id: unAuthorizedSaTokenAccess
    action: Block
    mode: strict
---
apiVersion: intent.security.nimbus.com/v1
kind: SecurityIntent
metadata:
  name: dns-manipulation-multiple-nsscoped
spec:
  intent:
    id: dnsManipulation
    action: Block
    mode: best-effort
    #mode: strict
---
apiVersion: intent.security.nimbus.com/v1
kind: SecurityIntentBinding
metadata:
  name: multiple-sis-nsscoped-binding
spec:
  intents:
    - name: pkg-mgr-exec-multiple-nsscoped
    - name: unauthorized-sa-token-access-multiple-nsscoped
    - name: dns-manipulation-multiple-nsscoped
  selector:
    cel:
      - labels["app"] == "nginx"
      #- labels["app"].equals("nginx")
      #- labels["app"].contains("nginx")
      #- labels["app"] in ["nginx"]
      #- labels["app"].startsWith("nginx")
      #- labels["app"].endsWith("nginx")
      #- labels["group"] == "group-1"
