# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Authors of Nimbus

apiVersion: intent.security.nimbus.com/v1alpha1
kind: SecurityIntent
metadata:
  name: pkg-mgr-exec-multiple-nsscoped
spec:
  intent:
    id: swDeploymentTools
    action: Block
---
apiVersion: intent.security.nimbus.com/v1alpha1
kind: SecurityIntent
metadata:
  name: unauthorized-sa-token-access-multiple-nsscoped
spec:
  intent:
    id: unAuthorizedSaTokenAccess
    action: Block
---
apiVersion: intent.security.nimbus.com/v1alpha1
kind: SecurityIntent
metadata:
  name: dns-manipulation-multiple-nsscoped
spec:
  intent:
    id: dnsManipulation
    action: Block
---
apiVersion: intent.security.nimbus.com/v1alpha1
kind: SecurityIntentBinding
metadata:
  name: multiple-sis-nsscoped-binding
spec:
  intents:
    - name: pkg-mgr-exec-multiple-nsscoped
    - name: unauthorized-sa-token-access-multiple-nsscoped
    - name: dns-manipulation-multiple-nsscoped
  selector:
    workloadSelector:
      matchLabels:
        app: nginx
