image:
  repository: 5gsec/nimbus-k8tls
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: "nimbus-k8tls"

serviceAccount:
  create: true
  automount: true
  name: "nimbus-k8tls"

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 64Mi

output:
  elasticsearch:
    enabled: false  
    host: "localhost"
    user: elastic
    port: 9200
    index: "findings"
    password: "" # Password in base64 encoded format
    ttlsecondsafterfinished: "10" # Amount of time to keep the pod around after job has been completed
