# Default values for nimbus-k8tls.

image:
  repository: 5gsec/nimbus-k8tls
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: "nimbus-k8tls"

serviceAccount:
  create: true
  automount: true
  name: "nimbus-k8tls"

securityContext:
  runAsNonRoot: true
  runAsUser: 65533

output:
  elasticsearch:
    enabled: false  
    host: "localhost"
    user: elastic
    port: 9200
    index: "findings"
    password: "" # Password in base64 encoded format
    ttlsecondsafterfinished: "10" # Amount of time to keep the pod around after job has been completed
    