# permissions for end users to view clusternimbuspolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusternimbuspolicy-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nimbus
    app.kubernetes.io/part-of: nimbus
    app.kubernetes.io/managed-by: kustomize
  name: clusternimbuspolicy-viewer-role
rules:
- apiGroups:
  - intent.security.nimbus.com
  resources:
  - clusternimbuspolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - intent.security.nimbus.com
  resources:
  - clusternimbuspolicies/status
  verbs:
  - get
