apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nimbus-operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nimbus-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: nimbus-operator
    namespace: nimbus
