apiVersion: intent.security.nimbus.com/v1
kind: SecurityIntent
metadata:
  name: block-access-to-sensitive-files
  namespace: default
spec:
  selector:
    cel:
      - "object.metadata.labels['kubernetes.io/hostname'] == 'master'"
  intent: 
    action: block
    mode: strict
    type: system
    resource: 
      - key: "paths"
        val: [ "/etc/shadow", "/etc/subuid", "/etc/subgid" ]
