apiVersion: v1
kind: Namespace
metadata:
  name: multiubuntu
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-1-service
  namespace: multiubuntu
  labels:
    service: ubuntu-1
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http-8000
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http-8080
  selector:
    group: group-1
    container: ubuntu-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-1-deployment
  namespace: multiubuntu
  labels:
    deployment: ubuntu-1
spec:
  replicas: 1
  selector:
    matchLabels:
      group: group-1
      container: ubuntu-1
  template:
    metadata:
      labels:
        group: group-1
        container: ubuntu-1
    spec:
      containers:
        - name: ubuntu-1-container
          image: 0x010/ubuntu-w-utils:latest
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-2-service
  namespace: multiubuntu
  labels:
    service: ubuntu-2
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http-8000
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http-8080
  selector:
    group: group-1
    container: ubuntu-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-2-deployment
  namespace: multiubuntu
  labels:
    deployment: ubuntu-2
spec:
  replicas: 1
  selector:
    matchLabels:
      group: group-1
      container: ubuntu-2
  template:
    metadata:
      labels:
        group: group-1
        container: ubuntu-2
    spec:
      containers:
      - name: ubuntu-2-container
        image: 0x010/ubuntu-w-utils:latest
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-3-service
  namespace: multiubuntu
  labels:
    service: ubuntu-3
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http-8000
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http-8080
  selector:
    group: group-1
    container: ubuntu-3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-3-deployment
  namespace: multiubuntu
  labels:
    deployment: ubuntu-3
spec:
  replicas: 1
  selector:
    matchLabels:
      group: group-1
      container: ubuntu-3
  template:
    metadata:
      labels:
        group: group-1
        container: ubuntu-3
    spec:
      containers:
      - name: ubuntu-3-container
        image: 0x010/ubuntu-w-utils:latest
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-4-service
  namespace: multiubuntu
  labels:
    service: ubuntu-4
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http-8000
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http-8080
  selector:
    group: group-2
    container: ubuntu-4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-4-deployment
  namespace: multiubuntu
  labels:
    deployment: ubuntu-4
spec:
  replicas: 1
  selector:
    matchLabels:
      group: group-2
      container: ubuntu-4
  template:
    metadata:
      labels:
        group: group-2
        container: ubuntu-4
    spec:
      containers:
      - name: ubuntu-4-container
        image: 0x010/ubuntu-w-utils:latest
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-5-service
  namespace: multiubuntu
  labels:
    service: ubuntu-5
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http-8000
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http-8080
  selector:
    group: group-2
    container: ubuntu-5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-5-deployment
  namespace: multiubuntu
  labels:
    deployment: ubuntu-5
spec:
  replicas: 1
  selector:
    matchLabels:
      group: group-2
      container: ubuntu-5
  template:
    metadata:
      labels:
        group: group-2
        container: ubuntu-5
    spec:
      containers:
      - name: ubuntu-5-container
        image: 0x010/ubuntu-w-utils:latest
---
apiVersion: v1
kind: Endpoints
metadata:
  namespace: multiubuntu
  name: external-service
subsets:
  - addresses:
      - ip: 143.248.36.38 # seungsoo.net
    ports:
      - port: 80
        protocol: TCP
        name: http-80
---
apiVersion: v1
kind: Service
metadata:
  namespace: multiubuntu
  name: external-service
  labels:
    service: external-service
spec:
  ports:
  - port: 8000
    targetPort: 80
    protocol: TCP
    name: http-80