apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ubuntu-3-file-dir-allow-from-source-path
  namespace: multiubuntu
spec:
  severity: 10
  message: "a critical directory was accessed"
  tags:
  - WARNING
  selector:
    matchLabels:
      container: ubuntu-3
  file:
    matchDirectories:
    - dir: /credentials/
      fromSource:
      - path: /bin/cat
  action:
    Allow