apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-runtimeclass
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
  - name: add-runtimeclass-to-deployment
    match:
      resources:
        kinds:
        - Deployment
        selector:
          matchLabels:
            app: nginx-test
    mutate:
      targets:
        - apiVersion: apps/v1
          kind: Deployment
      patchStrategicMerge:
        spec:
          template:
            spec:
              runtimeClassName: kata-qemu-snp