apiVersion: apps/v1
kind: Deployment
metadata:
  name: coco-test
  labels:
    app: nginx-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      runtimeClassName: kata-qemu-snp
      containers:
      - name: nginx
        image: 1hcoj/nginx