apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: run-pod-using-kata
spec:
  background: true
  validationFailureAction: Enforce
  mutateExistingOnPolicyUpdate: true
  rules:
  - name: coco-workload
    match:
      any:
      - resources:
          kinds:
          - v1/Pod
          namespaces:
          - default
          selector:
            matchLabels:
              app: nginx-test
    mutate:
      patchStrategicMerge:
        spec:
          +(runtimeClassName): kata-qemu-snp
      targets:
      - apiVersion: v1
        kind: Pod
        namespace: default
