apiVersion: intent.security.nimbus.com/v1
kind: SecurityIntent
metadata:
  name: coco-workload
spec:
  intent:
    id: cocoWorkload
    description: "Ensure workload is encryted by running the specified workload in a Confidential VM"
---
apiVersion: intent.security.nimbus.com/v1
kind: SecurityIntentBinding
metadata:
  name: coco-workload-binding
spec:
  intents:
    - name: coco-workload
  selector:
    any:
      - resources:
          kind: Pod
          namespace: default
          matchLabels:
            app: nginx-test