apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: {{ include "nimbus-k8tls.fullname" . }}-env
data:
  fluent-bit.conf: |
     [SERVICE]
        Flush        1
        Log_Level    info
        Parsers_File parsers.conf

     [INPUT]
        Name           tail
        Path           /tmp/compact_report.json
        Parser         json
        Tag            json.data
        DB             /tmp/compact_report.db
        Read_from_Head true
        Exit_On_Eof    true
    
     {{- if .Values.output.elasticsearch.enabled }}
     [OUTPUT]
        Name  es
        Match *
        Host  {{ .Values.output.elasticsearch.host }}
        Port  {{ .Values.output.elasticsearch.port }}
        Index {{ .Values.output.elasticsearch.index }}
        HTTP_User  {{ .Values.output.elasticsearch.user }}
        HTTP_Passwd ${ES_PASSWORD}
        tls      On
        tls.verify Off
        Suppress_Type_Name On
        Replace_Dots On
      {{- end }}

     [OUTPUT]
        Name stdout
        Match *