apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nimbus-k8tls.fullname" . }}
  labels:
    {{- include "nimbus-k8tls.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "nimbus-k8tls.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nimbus-k8tls.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "nimbus-k8tls.serviceAccountName" . }}
      containers:
        - name: {{ .Values.fullnameOverride }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.output.elasticsearch.enabled }}
          env:
          - name: TTLSECONDSAFTERFINISHED
            value: "{{ .Values.output.elasticsearch.ttlsecondsafterfinished }}"
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
