apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8tls
  labels:
    {{- include "nimbus-k8tls.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
