{{- if .Values.output.elasticsearch.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-password
  namespace: {{ include "nimbus-k8tls.fullname" . }}-env
  labels:
    {{- include "nimbus-k8tls.labels" . | nindent 4 }}
type: Opaque
data:
  es_password: {{ .Values.output.elasticsearch.password }} 
{{- end }}