{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nimbus-k8tls.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nimbus-k8tls.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8tls
  namespace: {{ include "nimbus-k8tls.fullname" . }}-env
  labels:
    {{- include "nimbus-k8tls.labels" . | nindent 4 }}
