apiVersion: intent.security.nimbus.com/v1
kind: ClusterSecurityIntentBinding
metadata:
  labels:
    app.kubernetes.io/name: clustersecurityintentbinding
    app.kubernetes.io/instance: clustersecurityintentbinding-sample
    app.kubernetes.io/part-of: nimbus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: nimbus
  name: clustersecurityintentbinding-sample
spec:
  # TODO(user): Add fields here
