apiVersion: intent.security.nimbus.com/v1
kind: SecurityIntent
metadata:
  name: escape-to-host
spec:
  intent:
    id: escapeToHost
    description: "A attacker can breach container boundaries and can gain access to the host machine"
    action: Block

---
apiVersion: intent.security.nimbus.com/v1
kind: ClusterSecurityIntentBinding
metadata:
  name: escape-to-host-binding
spec:
  intents:
    - name: escape-to-host
  selector:
    resources:
      - kind: Pod
        name: pod1
        namespace: ns1
        matchLabels:
          app: db
          env: dev

      - kind: Pod
        name: pod1
        namespace: ns2
        matchLabels:
          app: mongo
          env: prod
      
      - kind: Namespace
        name: default