apiVersion: intent.security.nimbus.com/v1
kind: SecurityIntent
metadata:
  name: allow-access-to-credentials-dir-ubuntu-3
  namespace: multiubuntu
spec:
  selector:
    match:
      any:
        - resources:
            matchLabels:
              container: "ubuntu-3"
            namespaces: ["multiubuntu"]
    cel:
      - "object.spec.file.matchDirectories.any(dir, dir == '/credentials/') && object.spec.file.fromSource.any(source, source == '/bin/cat')"
  intent:
    action: Allow
    mode: strict
    type: system
    resource:
      - key: "directories"
        val: ["/credentials/"]
      - key: "sourcePath"
        val: ["/bin/cat"]
