// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ResourceDataServiceClient is the client API for ResourceDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourceDataServiceClient interface {
	SendPodData(ctx context.Context, in *ResourceData, opts ...grpc.CallOption) (*Response, error)
}

type resourceDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceDataServiceClient(cc grpc.ClientConnInterface) ResourceDataServiceClient {
	return &resourceDataServiceClient{cc}
}

func (c *resourceDataServiceClient) SendPodData(ctx context.Context, in *ResourceData, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/nimbus.ResourceDataService/SendPodData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceDataServiceServer is the server API for ResourceDataService service.
// All implementations must embed UnimplementedResourceDataServiceServer
// for forward compatibility
type ResourceDataServiceServer interface {
	SendPodData(context.Context, *ResourceData) (*Response, error)
	mustEmbedUnimplementedResourceDataServiceServer()
}

// UnimplementedResourceDataServiceServer must be embedded to have forward compatible implementations.
type UnimplementedResourceDataServiceServer struct {
}

func (UnimplementedResourceDataServiceServer) SendPodData(context.Context, *ResourceData) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPodData not implemented")
}
func (UnimplementedResourceDataServiceServer) mustEmbedUnimplementedResourceDataServiceServer() {}

// UnsafeResourceDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceDataServiceServer will
// result in compilation errors.
type UnsafeResourceDataServiceServer interface {
	mustEmbedUnimplementedResourceDataServiceServer()
}

func RegisterResourceDataServiceServer(s grpc.ServiceRegistrar, srv ResourceDataServiceServer) {
	s.RegisterService(&ResourceDataService_ServiceDesc, srv)
}

func _ResourceDataService_SendPodData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceDataServiceServer).SendPodData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nimbus.ResourceDataService/SendPodData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceDataServiceServer).SendPodData(ctx, req.(*ResourceData))
	}
	return interceptor(ctx, in, info, handler)
}

// ResourceDataService_ServiceDesc is the grpc.ServiceDesc for ResourceDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nimbus.ResourceDataService",
	HandlerType: (*ResourceDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPodData",
			Handler:    _ResourceDataService_SendPodData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resourceData.proto",
}
