apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nimbus.fullname" . }}-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "nimbus.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "nimbus.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nimbus.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nimbus-operator
subjects:
  - kind: ServiceAccount
    name: nimbus-operator
    namespace: {{ .Release.Namespace }}