# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Authors of Nimbus

name: Latest release

on:
  push:
    branches:
      - main
      - "v*"
  create:
    branches:
      - "v*"

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-nimbus-image:
    if: github.repository == '5GSEC/nimbus'
    name: Build and push nimbus image
    uses: ./.github/workflows/release-image.yaml
    with:
      WORKING_DIRECTORY: .
    secrets: inherit

  release-adapters-image:
    if: github.repository == '5GSEC/nimbus'
    strategy:
      matrix:
        adapters: [ "nimbus-kubearmor", "nimbus-netpol" ]
    name: Build and push ${{ matrix.adapters }} adapter's image
    uses: ./.github/workflows/release-image.yaml
    with:
      WORKING_DIRECTORY: ./pkg/adapter/${{ matrix.adapters }}
    secrets: inherit
