# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Authors of Nimbus

name: PR checks

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    paths-ignore:
      - '**.md'
      - '**.sh'
      - 'docs/**'
      - 'LICENSE'

permissions: read-all

jobs:
  chainsaw-integration-tests:
    name: Integration-Test
    runs-on: ubuntu-latest
    needs: [build-nimbus-image, build-adapters-image]
    steps:
        - name: Checkout
          uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

        - name: Install helm
          id: helm
          uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Create k8s Kind Cluster
          uses: helm/kind-action@v1
          with:
            cluster_name: testing

        - name: Build image and load in the kind cluster
          run: |
            make docker-build
            kind load docker-image 5gsec/nimbus:latest --name=testing

        - name: Install Nimbus
          run: |
            helm upgrade --install nimbus-operator deployments/nimbus -n nimbus --create-namespace --set image.pullPolicy=Never

        - name: Wait for Nimbus to start
          run: |
            kubectl wait --for=condition=ready --timeout=5m -n nimbus pod -l app.kubernetes.io/name=nimbus
            kubectl get pods -A
            kubectl get crd nimbuspolicies.intent.security.nimbus.com -o yaml  | grep name:
            kubectl get crd clusternimbuspolicies.intent.security.nimbus.com -o yaml  | grep name:

        - name: Run Tests
          run: make integration-test

