# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Authors of Nimbus

name: release image
permissions: read-all

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        description: 'current working directory'
        required: true
        type: string

jobs:
  release-image:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get tag
        id: tag
        run: |
          if [ ${{ github.ref }} == "refs/heads/main" ]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push image
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: make docker-buildx TAG=${{ steps.tag.outputs.tag }}
