# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Authors of Nimbus

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nimbus-kubearmor-role
rules:
  - apiGroups:
      - intent.security.nimbus.com
    resources:
      - nimbuspolicies
      - clusternimbuspolicies
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - security.kubearmor.com
    resources:
      - kubearmorpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
